/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComposerRouteImport } from './routes/composer'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ApiPublicOauthInstagramCallbackRouteImport } from './routes/api/public/oauth/instagram/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposerRoute = ComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthInstagramCallbackRoute =
  ApiPublicOauthInstagramCallbackRouteImport.update({
    id: '/api/public/oauth/instagram/callback',
    path: '/api/public/oauth/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/composer': typeof ComposerRoute
  '/contas': typeof ContasRoute
  '/api/public/oauth/instagram/callback': typeof ApiPublicOauthInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/composer': typeof ComposerRoute
  '/contas': typeof ContasRoute
  '/api/public/oauth/instagram/callback': typeof ApiPublicOauthInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/composer': typeof ComposerRoute
  '/contas': typeof ContasRoute
  '/api/public/oauth/instagram/callback': typeof ApiPublicOauthInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/composer' | '/contas' | '/api/public/oauth/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/composer' | '/contas' | '/api/public/oauth/instagram/callback'
  id:
    | '__root__'
    | '/'
    | '/composer'
    | '/contas'
    | '/api/public/oauth/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComposerRoute: typeof ComposerRoute
  ContasRoute: typeof ContasRoute
  ApiPublicOauthInstagramCallbackRoute: typeof ApiPublicOauthInstagramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composer': {
      id: '/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof ComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/instagram/callback': {
      id: '/api/public/oauth/instagram/callback'
      path: '/api/public/oauth/instagram/callback'
      fullPath: '/api/public/oauth/instagram/callback'
      preLoaderRoute: typeof ApiPublicOauthInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComposerRoute: ComposerRoute,
  ContasRoute: ContasRoute,
  ApiPublicOauthInstagramCallbackRoute: ApiPublicOauthInstagramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
